In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statistics import mode
import random

In [ ]:
data= pd.read_csv('watson_healthcare_modified.csv')

In [ ]:
data.head()

EmployeeID  Age Attrition     BusinessTravel  DailyRate  Department  \
0     1313919   41        No      Travel_Rarely       1102  Cardiology   
1     1200302   49        No  Travel_Frequently        279   Maternity   
2     1060315   37       Yes      Travel_Rarely       1373   Maternity   
3     1272912   33        No  Travel_Frequently       1392   Maternity   
4     1414939   27        No      Travel_Rarely        591   Maternity   

   DistanceFromHome  Education EducationField  EmployeeCount  ...  \
0                 1          2  Life Sciences              1  ...   
1                 8          1  Life Sciences              1  ...   
2                 2          2          Other              1  ...   
3                 3          4  Life Sciences              1  ...   
4                 2          1        Medical              1  ...   

   RelationshipSatisfaction StandardHours  Shift  TotalWorkingYears  \
0                         1            80      0                  8   
1                         4            80      1                 10   
2                         2            80      0                  7   
3                         3            80      0                  8   
4                         4            80      1                  6   

   TrainingTimesLastYear WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
0                      0               1               6                  4   
1                      3               3              10                  7   
2                      3               3               0                  0   
3                      3               3               8                  7   
4                      3               3               2                  2   

   YearsSinceLastPromotion  YearsWithCurrManager  
0                        0                     5  
1                        1                     7  
2                        0                     0  
3                        3                     0  
4                        2                     2  

[5 rows x 35 columns]

In [ ]:
data.shape

(1676, 35)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1676 entries, 0 to 1675
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   EmployeeID                1676 non-null   int64 
 1   Age                       1676 non-null   int64 
 2   Attrition                 1676 non-null   object
 3   BusinessTravel            1676 non-null   object
 4   DailyRate                 1676 non-null   int64 
 5   Department                1676 non-null   object
 6   DistanceFromHome          1676 non-null   int64 
 7   Education                 1676 non-null   int64 
 8   EducationField            1676 non-null   object
 9   EmployeeCount             1676 non-null   int64 
 10  EnvironmentSatisfaction   1676 non-null   int64 
 11  Gender                    1676 non-null   object
 12  HourlyRate                1676 non-null   int64 
 13  JobInvolvement            1676 non-null   int64 
 14  JobLevel                

In [ ]:
data.drop('EmployeeID',axis=1,inplace=True)

In [ ]:
data.head(1)

Age Attrition  BusinessTravel  Department  DistanceFromHome  Education  \
0   41        No               1           1                 1          2   

  EducationField  EmployeeCount  EnvironmentSatisfaction  Gender  ...  \
0  Life Sciences              1                        2  Female  ...   

   RelationshipSatisfaction  StandardHours  Shift TotalWorkingYears  \
0                         1             80      0                 8   

   TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
0                      0               1               6                   4   

   YearsSinceLastPromotion YearsWithCurrManager  
0                        0                    5  

[1 rows x 33 columns]

In [ ]:
data['Attrition'].value_counts()

No     1477
Yes     199
Name: Attrition, dtype: int64

In [ ]:
data.isna().sum()

Age                         0
Attrition                   0
BusinessTravel              0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
Shift                       0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int

In [ ]:
data['DailyRate']

0       1102
1        279
2       1373
3       1392
4        591
        ... 
1671     471
1672    1125
1673     959
1674     466
1675     511
Name: DailyRate, Length: 1676, dtype: int64

In [ ]:
data.drop('DailyRate',axis=1,inplace=True)

In [ ]:
data['BusinessTravel'].unique()

array(['Travel_Rarely', 'Travel_Frequently', 'Non-Travel'], dtype=object)

In [ ]:
data['BusinessTravel']=data['BusinessTravel'].map({'Travel_Rarely':1,'Travel_Frequently':2,'Non-Travel':0})

In [ ]:
data['BusinessTravel'].unique()

array([1, 2, 0])

In [ ]:
data['Department'].unique()

array(['Cardiology', 'Maternity', 'Neurology'], dtype=object)

In [ ]:
data['Department']=data['Department'].map({'Cardiology':1,'Maternity':2,'Neurology':0})

In [ ]:
data['Department'].unique()

array([1, 2, 0])

In [ ]:
data.head(1)

Age Attrition  Department  DistanceFromHome  Education EducationField  \
0   41        No           1                 1          2  Life Sciences   

   EnvironmentSatisfaction  Gender  JobInvolvement  JobLevel  ... OverTime  \
0                        2       1               3         2  ...        1   

   PercentSalaryHike PerformanceRating  RelationshipSatisfaction  \
0                 11                 3                         1   

   StandardHours  Shift TotalWorkingYears  YearsAtCompany  YearsInCurrentRole  \
0             80      0                 8               6                   4   

   YearsSinceLastPromotion  
0                        0  

[1 rows x 27 columns]

In [ ]:
data['EducationField'].unique()

array(['Life Sciences', 'Other', 'Medical', 'Marketing',
       'Technical Degree', 'Human Resources'], dtype=object)

In [ ]:
data['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [ ]:
data['Gender']=data['Gender'].map({'Female':1,'Male':0})

In [ ]:
data['Gender'].unique()

array([1, 0])

In [ ]:
data['YearsSinceLastPromotion'].unique()

array([ 0,  1,  3,  2,  7,  4,  8,  6,  5, 15,  9, 13, 12, 10, 11, 14])

In [ ]:
data.drop('TrainingTimesLastYear',axis=1,inplace=True)

In [ ]:
data['Shift'].unique()

array([0, 1, 3, 2])

In [ ]:
data['Shift'].value_counts()

0    708
1    684
2    185
3     99
Name: Shift, dtype: int64

In [ ]:
data.drop('WorkLifeBalance',axis=1,inplace=True)

In [ ]:
data.drop('YearsWithCurrManager',axis=1,inplace=True)

In [ ]:
data['BusinessTravel'].unique()

array([1, 2, 0])

In [ ]:
data.drop('BusinessTravel',axis=1,inplace=True)

In [ ]:
data.drop('EmployeeCount',axis=1,inplace=True)

In [ ]:
data['OverTime'].unique()

array(['Yes', 'No'], dtype=object)

In [ ]:
data['OverTime']=data['OverTime'].map({'Yes':1,'No':0})

In [ ]:
data.drop('HourlyRate',axis=1,inplace=True)

In [ ]:
data.drop('EnvironmentSatisfaction',axis=1,inplace=True)

In [ ]:
data.head(1)

Age Attrition  Department  DistanceFromHome  Education EducationField  \
0   41        No           1                 1          2  Life Sciences   

   Gender  JobInvolvement  JobLevel JobRole  ...  OverTime PercentSalaryHike  \
0       1               3         2   Nurse  ...         1                11   

   PerformanceRating  RelationshipSatisfaction  StandardHours Shift  \
0                  3                         1             80     0   

   TotalWorkingYears  YearsAtCompany  YearsInCurrentRole  \
0                  8               6                   4   

   YearsSinceLastPromotion  
0                        0  

[1 rows x 26 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1676 entries, 0 to 1675
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Age                       1676 non-null   int64 
 1   Attrition                 1676 non-null   int64 
 2   Department                1676 non-null   int64 
 3   DistanceFromHome          1676 non-null   int64 
 4   Education                 1676 non-null   int64 
 5   EducationField            1676 non-null   object
 6   Gender                    1676 non-null   int64 
 7   JobInvolvement            1676 non-null   int64 
 8   JobLevel                  1676 non-null   int64 
 9   JobRole                   1676 non-null   object
 10  JobSatisfaction           1676 non-null   int64 
 11  MonthlyIncome             1676 non-null   int64 
 12  MonthlyRate               1676 non-null   int64 
 13  NumCompaniesWorked        1676 non-null   int64 
 14  OverTime                

In [ ]:
data.drop('Over18',axis=1,inplace=True)

In [ ]:
data['Attrition'].unique()

array(['No', 'Yes'], dtype=object)

In [ ]:
data['Attrition']=data['Attrition'].map({'No':0,'Yes':1})

In [ ]:
data['Attrition'].unique()

array([0, 1])

In [ ]:
data['Education'].unique()

array([2, 1, 4, 3, 5])

In [ ]:
data['JobRole'].unique()

array(['Nurse', 'Other', 'Therapist', 'Administrative', 'Admin'],
      dtype=object)

In [ ]:
data['MaritalStatus'].unique()

array(['Single', 'Married', 'Divorced'], dtype=object)

In [ ]:
data['MaritalStatus'].value_counts()

Married     777
Single      522
Divorced    377
Name: MaritalStatus, dtype: int64

In [ ]:
data.drop('MaritalStatus',axis=1,inplace=True)

In [ ]:
data['RelationshipSatisfaction'].unique()

array([1, 4, 2, 3])

In [ ]:
data['PercentSalaryHike'].unique()

array([11, 23, 15, 12, 13, 20, 22, 21, 17, 14, 16, 18, 19, 24, 25])

In [ ]:
data['PerformanceRating'].unique()

array([3, 4])

In [ ]:
data.drop('StandardHours',axis=1,inplace=True)

In [ ]:
data.head(1)

Age  Attrition  Department  DistanceFromHome  Education  EducationField  \
0   41          0           1                 1          2               1   

   Gender  JobInvolvement  JobLevel JobRole  ...  NumCompaniesWorked  \
0       1               3         2   Nurse  ...                   8   

   OverTime  PercentSalaryHike  PerformanceRating  RelationshipSatisfaction  \
0         1                 11                  3                         1   

   Shift  TotalWorkingYears  YearsAtCompany  YearsInCurrentRole  \
0      0                  8               6                   4   

   YearsSinceLastPromotion  
0                        0  

[1 rows x 23 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
LB= LabelEncoder()

In [ ]:
data['EducationField']=LB.fit_transform(data['EducationField'])

In [ ]:
data['JobRole']=LB.fit_transform(data['JobRole'])

In [ ]:
data.dtypes

Age                         int64
Attrition                   int64
Department                  int64
DistanceFromHome            int64
Education                   int64
EducationField              int64
Gender                      int64
JobInvolvement              int64
JobLevel                    int64
JobRole                     int64
JobSatisfaction             int64
MonthlyIncome               int64
MonthlyRate                 int64
NumCompaniesWorked          int64
OverTime                    int64
PercentSalaryHike           int64
PerformanceRating           int64
RelationshipSatisfaction    int64
Shift                       int64
TotalWorkingYears           int64
YearsAtCompany              int64
YearsInCurrentRole          int64
YearsSinceLastPromotion     int64
dtype: object

In [ ]:
X=data.drop('Attrition',axis=True)

In [ ]:
X.head(2)

Age  Department  DistanceFromHome  Education  EducationField  Gender  \
0   41           1                 1          2               1       1   
1   49           2                 8          1               1       0   

   JobInvolvement  JobLevel  JobRole  JobSatisfaction  ...  \
0               3         2        2                4  ...   
1               2         2        3                2  ...   

   NumCompaniesWorked  OverTime  PercentSalaryHike  PerformanceRating  \
0                   8         1                 11                  3   
1                   1         0                 23                  4   

   RelationshipSatisfaction  Shift  TotalWorkingYears  YearsAtCompany  \
0                         1      0                  8               6   
1                         4      1                 10              10   

   YearsInCurrentRole  YearsSinceLastPromotion  
0                   4                        0  
1                   7                        1  

[2 rows x 22 columns]

In [ ]:
y=data['Attrition']

In [ ]:
y.head()

0    0
1    0
2    1
3    0
4    0
Name: Attrition, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=12)

In [ ]:
X_train.head(2)

Age  Department  DistanceFromHome  Education  EducationField  Gender  \
1571   30           0                 2          1               3       0   
300    41           1                 2          4               1       0   

      JobInvolvement  JobLevel  JobRole  JobSatisfaction  ...  \
1571               2         1        2                4  ...   
300                3         4        1                2  ...   

      NumCompaniesWorked  OverTime  PercentSalaryHike  PerformanceRating  \
1571                   0         0                 13                  3   
300                    1         0                 19                  3   

      RelationshipSatisfaction  Shift  TotalWorkingYears  YearsAtCompany  \
1571                         4      0                  6               5   
300                          2      0                 22              22   

      YearsInCurrentRole  YearsSinceLastPromotion  
1571                   3                        1  
300                   10                        0  

[2 rows x 22 columns]

In [ ]:
y_train.head()

1571    0
300     0
1478    0
1331    0
1583    0
Name: Attrition, dtype: int64

In [ ]:
X_test.head(2)

Age  Department  DistanceFromHome  Education  EducationField  Gender  \
1323   32           1                 2          4               2       0   
1066   28           2                 1          3               1       0   

      JobInvolvement  JobLevel  JobRole  JobSatisfaction  ...  \
1323               2         2        2                2  ...   
1066               2         1        3                3  ...   

      NumCompaniesWorked  OverTime  PercentSalaryHike  PerformanceRating  \
1323                   7         1                 12                  3   
1066                   1         0                 14                  3   

      RelationshipSatisfaction  Shift  TotalWorkingYears  YearsAtCompany  \
1323                         3      0                  7               2   
1066                         4      1                  1               1   

      YearsInCurrentRole  YearsSinceLastPromotion  
1323                   2                        2  
1066                   0                        0  

[2 rows x 22 columns]

In [ ]:
y_test.head()

1323    1
1066    0
245     0
1267    0
291     0
Name: Attrition, dtype: int64

In [ ]:
model=keras.Sequential([
    keras.layers.Dense(50,input_shape=(22,),activation="sigmoid"),
      keras.layers.Dense(20,activation="softmax"),
      keras.layers.Dense(2,activation="sigmoid"),
    ])

model.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=["accuracy"])

model.fit(X_train,y_train,epochs=10)

Epoch 1/10
40/40 [==============================] - 1s 2ms/step - loss: 0.5690 - accuracy: 0.8831
Epoch 2/10
40/40 [==============================] - 0s 2ms/step - loss: 0.4918 - accuracy: 0.8831
Epoch 3/10
40/40 [==============================] - 0s 2ms/step - loss: 0.4467 - accuracy: 0.8831
Epoch 4/10
40/40 [==============================] - 0s 2ms/step - loss: 0.4036 - accuracy: 0.8831
Epoch 5/10
40/40 [==============================] - 0s 2ms/step - loss: 0.3759 - accuracy: 0.8831
Epoch 6/10
40/40 [==============================] - 0s 2ms/step - loss: 0.3664 - accuracy: 0.8831
Epoch 7/10
40/40 [==============================] - 0s 2ms/step - loss: 0.3615 - accuracy: 0.8831
Epoch 8/10
40/40 [==============================] - 0s 2ms/step - loss: 0.3589 - accuracy: 0.8831
Epoch 9/10
40/40 [==============================] - 0s 2ms/step - loss: 0.3567 - accuracy: 0.8831
Epoch 10/10
40/40 [==============================] - 0s 2ms/step - loss: 0.3551 - accuracy: 0.8831


In [ ]:
model.evaluate(X_train,y_train)

40/40 [==============================] - 0s 3ms/step - loss: 0.3608 - accuracy: 0.8831


[0.36079591512680054, 0.8830549120903015]